---
title: 'Covid data'
output:
    html_document:
        code_folding: hide
        toc: true
        toc_float: true
        toc_depth: 3
---

```{r lib}
library(ggplot2)
```

```{r}
run.fresh <- FALSE
```

```{r download_data, cache=TRUE, eval=run.fresh}
# NOTE: run this chunk to redownload the JHU data
current.date <- Sys.Date()

# File with data to be analyzed
dload.filename <- paste0('covid',curre.date,'.csv')

# Github with JHU data
# https://github.com/CSSEGISandData/COVID-19

# build urls
prefix <- 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/'

file.list <- list(US=list(confirmed='time_series_covid19_confirmed_US.csv',
                           deaths='time_series_covid19_deaths_US.csv'),
                   Global=list(confirmed='time_series_covid19_confirmed_global.csv',
                           deaths='time_series_covid19_deaths_global.csv'))

if(!dir.exists('data')) dir.create('data')

for(name in names(file.list)){
  for(type in names(file.list[[name]])){
    url <- file.path(prefix, file.list[[name]][[type]])
    download.file(url, file.path('data', file.list[[name]][[type]]))
  }
}
# These are from the Tableau website which derive from the JHU data
# URL
# link <- 'https://data.world/covid-19-data-resource-hub/covid-19-case-counts/workspace/file?filename=COVID-19+Cases.csv'
# NOTE: This asks for login
#
# Google sheets file: https://docs.google.com/spreadsheets/d/14quQPFErG-hlpsrNgYcX85vW7JMMK5X2vNZrafRcH8c/edit#gid=1592210746
# NOTE: You will first need to save a copy to google drive
#

```

The data used in this analysis was downloaded on: `r current.date`
The analysis was last run on: `r Sys.Date()`

```{r global_options}
knitr::opts_chunk$set(warning=FALSE, message=FALSE,
                      fig.width=10, fig.height=7)
```

# Load data

```{r load_data, cache=TRUE, dependson='download_data'}
covid <- read.csv(dload.filename, sep=',', header=TRUE)
covid$new_date <- as.Date(covid$Date, format='%m/%d/%y')
covid.us <- covid[covid$Country_Region == 'US',]
covid.us.time <- covid.us[covid.us$Table.Names == 'JHU Time Series',]
covid.us.daily <- covid.us[covid.us$Table.Names == 'JHU Daily Summary',]
```

# Plots

## Cases by date

```{r plots}
p <- ggplot(covid.us.time, aes(y=Cases, x=new_date, color=Case_Type)) +
    geom_point(alpha=0.5) + geom_line()# + facet_wrap(~ Province_State, nrow=9, scales='free')
p
```

```{r confirmed, cache=TRUE, dependson='load_data'}
df.confirmed <- covid.us.time[covid.us.time$Case_Type == 'Confirmed',]
```

## Deaths by Province

```{r deaths, cache=TRUE, dependson='load_data'}
df.deaths <- covid.us.time[covid.us.time$Case_Type == 'Deaths',]
p <- ggplot(df.deaths, aes(y=Cases, x=new_date, color=Province_State)) +
    geom_point(alpha=0.5) + geom_line()

p
```

```{r sum_deaths, cache=TRUE, dependson='deaths'}
dates <- unique(df.deaths$new_date)
states <- unique(df.deaths$Province_State)
sum.deaths <- data.frame()
cols.to.subset <- c('Case_Type','Long','Lat','Country_Region','Date','Province_State','new_date')
sum.states <- NULL
for(d in as.character(dates)){
    for(s in states){
        #cat(d,s,'\n')
        subset <- df.deaths[df.deaths$new_date == d & df.deaths$Province_State == s,]
        if(dim(subset)[1] > 0){
            subset.sum <- sum(subset$Cases)
            sum.states <- c(sum.states, subset.sum)
            sum.deaths <- rbind(sum.deaths, subset[1,cols.to.subset])
        }
    }
}
sum.deaths <- cbind(sum.deaths, Cases=sum.states)
```

```{r sum_confirmed, cache=TRUE, dependson='confirmed'}
dates <- unique(df.confirmed$new_date)
states <- unique(df.confirmed$Province_State)
sum.confirmed <- data.frame()
sum.states <- NULL
for(d in as.character(dates)){
    for(s in states){
        #cat(d,s,'\n')
        subset <- df.confirmed[df.confirmed$new_date == d & df.confirmed$Province_State == s,]
        if(dim(subset)[1] > 0){
            subset.sum <- sum(subset$Cases)
            sum.states <- c(sum.states, subset.sum)
            sum.confirmed <- rbind(sum.confirmed, subset[1,cols.to.subset])
        }
    }
}
sum.confirmed <- cbind(sum.confirmed, Cases=sum.states)
```

## Confirmed by State (daily values summed)

```{r}
p <- ggplot(sum.confirmed, aes(x=new_date, y=Cases, color=Province_State)) + geom_line()
p
```

## Deaths by State (daily values summed)

```{r}
p <- ggplot(sum.deaths, aes(x=new_date, y=Cases, color=Province_State)) + geom_line()
p
```

<!--
## Cumulative confirmed by State
-->

```{r, cache=TRUE, dependson='sum_confirmed'}
cumsum.confirmed <- data.frame()
total.confirmed <- data.frame()
total.confirmed.vec <- NULL
for(s in states){
    subset <- sum.confirmed[sum.confirmed$Province_State == s,]
    subset <- subset[order(subset$new_date),]
    subset$cumsum_cases <- cumsum(subset$Cases)
    total.confirmed.vec <- c(total.confirmed.vec, sum(subset$Cases))
    cumsum.confirmed <- rbind(cumsum.confirmed, subset)
    total.confirmed <- rbind(total.confirmed, subset[1,cols.to.subset])
}
total.confirmed <- cbind(total.confirmed, total.confirmed=total.confirmed.vec)
```

```{r, eval=FALSE}
p <- ggplot(cumsum.confirmed, aes(x=new_date, y=cumsum_cases, color=Province_State)) +
    geom_line()
p
```

## Cumulative deaths by State

```{r, cache=TRUE, dependson='sum_deaths'}
cumsum.deaths <- data.frame()
total.deaths <- data.frame()
total.deaths.vec <- NULL
for(s in states){
    subset <- sum.deaths[sum.deaths$Province_State == s,]
    subset <- subset[order(subset$new_date),]
    subset$cumsum_cases <- cumsum(subset$Cases)
    total.deaths.vec <- c(total.deaths.vec, sum(subset$Cases))
    cumsum.deaths <- rbind(cumsum.deaths, subset)
    total.deaths <- rbind(total.deaths, subset[1,cols.to.subset])
}
total.deaths <- cbind(total.deaths, total.deaths=total.deaths.vec)
```

```{r}
p <- ggplot(cumsum.deaths, aes(x=new_date, y=cumsum_cases, color=Province_State)) +
    geom_line()
p
```

## Values plotted on map {.tabset}

```{r}
# NOTE: x-axis limits
xmax <- -67
xmin <- -125

# NOTE: y-axis limits
ymin <- 25
ymax <- 50
```

### Confirmed

```{r}
cols <- colorRampPalette(RColorBrewer::brewer.pal(9, 'Reds'))(255)
p <- ggplot(df.confirmed[df.confirmed$Cases > 0,],
            aes(x=Long, y=Lat, size=log2(Cases))) +
    geom_point(alpha=0.05, color='darkblue') + xlim(xmin,xmax) + ylim(ymin, ymax) + theme_bw() +
    scale_size_continuous(breaks=c(0, 5, 10, 15),
                           labels=2^(c(0, 5, 10, 15)),
                           name='Confirmed')
p
```

### Deaths

```{r}
p <- ggplot(df.deaths[df.deaths$Cases > 0,], 
            aes(x=Long, y=Lat, size=log2(Cases))) +
    geom_point(alpha=0.1, color='darkred') + xlim(xmin,xmax) + ylim(ymin, ymax) + theme_bw() +
    scale_size_continuous(breaks=c(0, 5, 10),
                           labels=2^c(0,5,10),
                           name='Deaths')
p
```

### Together

```{r}
p <- ggplot(covid.us.time[covid.us.time$Cases > 0,], 
            aes(x=Long, y=Lat, color=Case_Type, size=log2(Cases))) +
    geom_point(alpha=0.05) + xlim(xmin,xmax) + ylim(ymin, ymax) + theme_bw() +
    scale_color_manual(values=c('blue','darkred')) +
    scale_size_continuous(breaks=c(0, 5, 10),
                           labels=2^c(0,5,10),
                           name='Cases')
p
```

## Density {.tabset}

### Confirmed


```{r}
p <- ggplot(df.confirmed[df.confirmed$Cases > 0,], aes(x=Long, y=Lat)) +
    stat_density_2d(aes(fill=after_stat(level)), geom='polygon', alpha=0.5) +
    scale_fill_continuous(type='viridis') +
    geom_point(alpha=0.05) + xlim(xmin,xmax) + ylim(ymin, ymax) + theme_bw() +
    scale_color_continuous(type='viridis')
p
```

### Deaths

```{r}
p <- ggplot(df.deaths[df.deaths$Cases > 0,], aes(x=Long, y=Lat)) +
    stat_density_2d(aes(fill=after_stat(level)), geom='polygon', alpha=0.5) +
    scale_fill_continuous(type='viridis') +
    geom_point(alpha=0.05) + xlim(xmin,xmax) + ylim(ymin, ymax) + theme_bw() +
    scale_color_continuous(type='viridis')
p
```

# sessionInfo

```{r collapse=FALSE}
sessionInfo()
```
